### ISSUE TITLE
Combine efforts?

### ISSUE THREAD

**Issue by xjamundx** [thomasloh/5to6#1]
A few weeks ago I created this...and just went to try to publish it today:
https://github.com/5to6/5to6

Looks like you beat me to it by a few days!

I think architecturally our 2 things look a bit different, but I think we have the same goals. Would you have any interesting in combining?

**Comment by thomasloh** [comment]
@xjamundx yeah actually this was initially built on an adhoc case and I haven't had the time to improve it as other things cropped up
